---
clone:
  git:
    image: plugins/git
    depth: 1
pipeline:
  lint:
    image: node:8.12
    commands:
      - npm i npm@latest -g
      - npm install
      - npm run build-test
      - npm run test
